---
title: "Reproducible Research Course Project 1"
author: "Diego Vargas"
date: "January 9, 2016"
output: html_document
---


#Loading and processing the data

```{r, echo=TRUE}
cls = c("integer", "character", "integer")
df <- read.csv("activity.csv", head=TRUE, colClasses=cls, na.strings="NA")
head(df)
df$date <- as.Date(df$date)
df_ign <- subset(df, !is.na(df$steps))

```

#What is mean total number of steps taken per day?

```{r, echo=TRUE}
dailysteps <- tapply(df_ign$steps, df_ign$date, sum, na.rm=TRUE, simplify=T)
dailysteps <- dailysteps[!is.na(dailysteps)]

hist(x=dailysteps,
     col="red",
     breaks=20,
     xlab="Daily total steps",
     ylab="Frequency",
     main="Total number of steps taken each day")

mean(dailysteps)
median(dailysteps)

```


#What is the average daily activity pattern?

```{r, echo=TRUE}

int_avg <- tapply(df_ign$steps, df_ign$interval, mean, na.rm=TRUE, simplify=T)
df_ia <- data.frame(interval=as.integer(names(int_avg)), avg=int_avg)

with(df_ia,
     plot(interval,
          avg,
          type="l",
          xlab="5-minute intervals",
          ylab="average steps in the interval across all days"))

max_steps <- max(df_ia$avg)
df_ia[df_ia$avg == max_steps, ]
```

#Imputing missing values

```{r,echo=TRUE}

sum(is.na(df$steps))
df_impute <- df
ndx <- is.na(df_impute$steps)
int_avg <- tapply(df_ign$steps, df_ign$interval, mean, na.rm=TRUE, simplify=T)
df_impute$steps[ndx] <- int_avg[as.character(df_impute$interval[ndx])]

new_dailysteps <- tapply(df_impute$steps, df_impute$date, sum, na.rm=TRUE, simplify=T)

hist(x=new_dailysteps,
     col="red",
     breaks=20,
     xlab="daily steps",
     ylab="frequency",
     main="Total number of steps taken each day")

mean(new_dailysteps)
median(new_dailysteps)
```
###The mean doesn't change but the median does. With a slight variation it's now the same as the mean.


#Are there differences in activity patterns between weekdays and weekends?

```{r,echo=TRUE}

is_weekday <- function(d) {
  wd <- weekdays(d)
  ifelse (wd == "Saturday" | wd == "Sunday", "weekend", "weekday")
}

wx <- sapply(df_impute$date, is_weekday)
df_impute$wk <- as.factor(wx)
head(df_impute)

wk_df <- aggregate(steps ~ wk+interval, data=df_impute, FUN=mean)

library(lattice)
xyplot(steps ~ interval | factor(wk),
       layout = c(1, 2),
       xlab="Interval",
       ylab="Number of steps",
       type="l",
       lty=1,
       data=wk_df)
```

